export { default as Ava } from "./images/ava.jpg";
export { default as Book } from "./images/book.png";
export { default as CreateNote } from "./images/createNote.png";
export { default as Cube } from "./images/cube.png";
export { default as DeleteNote } from "./images/deleteNote.png";
export { default as Hammer } from "./images/hammer.png";
export { default as History } from "./images/history.png";
export { default as Statistics } from "./images/statistics.png";

export { default as Bell } from "./svg/bell.svg";
export { default as Company } from "./svg/company.svg";
export { default as FolderPlus } from "./svg/folderPlus.svg";
export { default as Integration } from "./svg/integration.svg";
export { default as Key } from "./svg/key.svg";
export { default as Logout } from "./svg/logout.svg";
export { default as Person } from "./svg/person.svg";
export { default as Security } from "./svg/security.svg";
export { default as Settings } from "./svg/settings.svg";
export { default as Hide } from "./svg/hide.svg";
